pull_request_rules:
  - name: Automatic merge when all status checks pass
    conditions:
      - status-success=security/snyk (Bifravst)
      - status-success=tests
    actions:
      label:
        add:
         - auto-merged
      merge:
        method: rebase
        rebase_fallback: squash
        strict: true
